### ISSUE TITLE
get_operation will return wrong number

### ISSUE THREAD

**Issue by Lukkario** [IIS-ZPI/ZPI_2019_Dzienni_IO4_SpiceTech#32]
https://github.com/IIS-ZPI/ZPI_2019_Dzienni_IO4_SpiceTech/blob/11b0ee9d94c9f02bb60310e02843b5a7483ba16b/src/read_operation.py#L13-L15

No matter what user input is the function will return it.

Making this in while loop keep test in infinite loop for wrong input, after fix.

**Comment by BokononPL** [comment]
fixed
